# Generated by Django 5.2.6 on 2026-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_transfer',
            field=models.BooleanField(default=False, help_text='Allow user to transfer between balance and profit'),
        ),
    ]
