# Generated by Django 5.2.6 on 2026-02-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_can_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio/description of the trader'),
        ),
        migrations.AddField(
            model_name='trader',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('crypto', 'Crypto'), ('stocks', 'Stocks'), ('healthcare', 'Healthcare'), ('financial', 'Financial Services'), ('options', 'Options'), ('tech', 'Tech'), ('etf', 'ETF')], default='all', help_text='Trading category for filtering', max_length=50),
        ),
        migrations.AddField(
            model_name='trader',
            name='cumulative_copiers',
            field=models.PositiveIntegerField(default=0, help_text='Total cumulative copiers (all time)'),
        ),
        migrations.AddField(
            model_name='trader',
            name='cumulative_earnings_copiers',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative earnings of all copiers', max_digits=15),
        ),
        migrations.AddField(
            model_name='trader',
            name='followers',
            field=models.PositiveIntegerField(default=0, help_text='Number of followers'),
        ),
        migrations.AddField(
            model_name='trader',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum drawdown percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='trader',
            name='portfolio_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Portfolio allocation, e.g. [{"name": "ETF", "percentage": 25}, {"name": "Crypto", "percentage": 25}, {"name": "Futures", "percentage": 50}]'),
        ),
        migrations.AddField(
            model_name='trader',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Badge tags, e.g. ["Trending Investors", "Rising Stars"]'),
        ),
        migrations.AddField(
            model_name='trader',
            name='top_traded',
            field=models.JSONField(blank=True, default=list, help_text='Top traded assets with stats, e.g. [{"name": "Apple Inc", "ticker": "AAPL", "avg_profit": 12.5, "avg_loss": -3.2, "profitable_pct": 78}]'),
        ),
        migrations.AddField(
            model_name='trader',
            name='trading_days',
            field=models.CharField(default='0', help_text="Trading days experience, e.g. '500+', '1200'", max_length=50),
        ),
        migrations.AddField(
            model_name='trader',
            name='trend_direction',
            field=models.CharField(choices=[('upward', 'Upward'), ('downward', 'Downward')], default='upward', help_text='Chart trend direction for earnings display (upward or downward)', max_length=10),
        ),
    ]
