# Generated by Django 5.2.6 on 2026-02-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trader_bio_trader_category_trader_cumulative_copiers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradercopy',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='Whether user has requested to cancel copying (pending admin approval)'),
        ),
        migrations.AddField(
            model_name='usertradercopy',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the cancel request was made', null=True),
        ),
    ]
