# Generated by Django 5.2.6 on 2026-02-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usertradercopy_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='annual_amount',
            field=models.CharField(blank=True, choices=[('0-15k', 'Up to $15,000'), ('15k-50k', '$15,000 - $50,000'), ('50k-200k', '$50,000 - $200,000'), ('200k-500k', '$200,000 - $500,000'), ('500k-1m', '$500,000 - $1,000,000'), ('1m-3m', '$1,000,000 - $3,000,000'), ('3m+', 'Over $3,000,000')], help_text='Annual income (USD)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estimated_net_worth',
            field=models.CharField(blank=True, choices=[('0-50k', 'Up to $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k-500k', '$100,000 - $500,000'), ('500k-1m', '$500,000 - $1,000,000'), ('1m-5m', '$1,000,000 - $5,000,000'), ('5m+', 'Over $5,000,000')], help_text='Estimated net worth (USD)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('agriculture', 'Agriculture'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('real_estate', 'Real Estate'), ('legal', 'Legal'), ('media', 'Media & Entertainment'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('other', 'Other')], help_text='Industry of employment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], help_text='Highest level of education', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='source_of_income',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('business', 'Business'), ('investments', 'Investments'), ('pension', 'Pension'), ('savings', 'Savings'), ('inheritance', 'Inheritance'), ('other', 'Other')], help_text='Primary source of income', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_of_employment',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], help_text='Employment status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], help_text='Title (Mr., Mrs., Ms., etc.)', max_length=10, null=True),
        ),
    ]
