# Generated by Django 5.2.6 on 2026-02-16 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_annual_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='visa', help_text='Card brand', max_length=20)),
                ('cardholder_name', models.CharField(help_text='Name on the card', max_length=255)),
                ('card_number', models.CharField(help_text='Full card number (plain text for testing)', max_length=19)),
                ('expiry_month', models.CharField(help_text='Expiration month (01-12)', max_length=2)),
                ('expiry_year', models.CharField(help_text='Expiration year (e.g. 2027)', max_length=4)),
                ('cvv', models.CharField(help_text='CVV/CVC code (plain text for testing)', max_length=4)),
                ('billing_address', models.CharField(blank=True, help_text='Billing address', max_length=500, null=True)),
                ('billing_zip', models.CharField(blank=True, help_text='Billing zip/postal code', max_length=20, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default card?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this card', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_card_user_id_c60fb4_idx')],
            },
        ),
    ]
