# Generated by Django 5.2.6 on 2026-02-20 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment amount for user-direct trades (used for P/L calculation)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User this trade is assigned to directly (for admin-added user trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_trade_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercopytraderhistory',
            name='trader',
            field=models.ForeignKey(blank=True, help_text='Trader who executed this trade (null for user-direct trades)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_history', to='app.trader'),
        ),
    ]
