# Generated by Django 6.0.1 on 2026-03-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_direct_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('other', 'Other')], default='other', help_text='Highest level of education', max_length=50, null=True),
        ),
    ]
