# Generated by Django 6.0.5 on 2026-05-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fix_decimal_overflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='trading_days',
        ),
        migrations.AddField(
            model_name='trader',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Profit share percentage (e.g. 50.00 means 50%)', max_digits=5),
        ),
    ]
