# Generated by Django 6.0.5 on 2026-05-22 10:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_adminwallet_currency_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercopytraderhistory',
            name='custom_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Custom image for this trade (shown instead of the default market icon)', max_length=255, null=True, verbose_name='custom_image'),
        ),
    ]
