# Generated by Django 6.0.5 on 2026-05-29 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_custom_image_to_usercopytraderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload the stock logo/image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
