# Generated by Django 6.0.5 on 2026-08-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_transferhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Maximum amount the user can transfer at a time (only enforced when transfer_limit_enabled is True)', max_digits=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transfer_limit_enabled',
            field=models.BooleanField(default=False, help_text='Enforce a maximum amount per transfer for this user'),
        ),
    ]
