# Generated by Django 6.0.5 on 2026-09-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_customuser_transfer_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='transfer_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Maximum total amount (balance<->profit, combined) the user can transfer per calendar day (only enforced when transfer_limit_enabled is True)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='transfer_limit_enabled',
            field=models.BooleanField(default=False, help_text='Enforce a maximum total transfer amount per day for this user'),
        ),
    ]
